# Generated by Django 4.2.7 on 2023-11-11 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'heic'])]),
        ),
    ]
